version: "3.7"
services: 
    wireguard:
        image: linuxserver/wireguard
        container_name: wireguard
        privileged: true
        networks:
           - wireguard
        cap_add:
        - NET_ADMIN
        - SYS_MODULE
        environment:
        - PUID=1001
        - PGID=1001
        - TZ=Asia/Tokyo
        volumes:
        - ./config:/config
        - /lib/modules:/lib/modules
        ports:
        - 51820:51820/udp
        sysctls:
        - net.ipv4.conf.all.src_valid_mark=1
        - net.ipv6.conf.all.disable_ipv6=0
        restart: unless-stopped

    radcast_recorder:
        depends_on:
          - wireguard
        container_name: recorder
        build: .
        volumes: 
          - ./:/home/radcast
        tty: true
        network_mode: service:wireguard
        restart: unless-stopped

    radcast_podcast:
        build: .
        container_name: podcast
        volumes: 
          - ./:/home/radcast
        tty: true
        ports:
          - 3355:3355
        restart: unless-stopped

networks:
    wireguard:
      driver: bridge